
# configure file for dynamic rupture simulations 
# in YAML format

# number of processors
nproc : 4
# simulation time length (in seconds)
simu_time_max : 10.05

# mesh dir
mesh_dir : data
# output dir
data_dir : data

# snapshot output: skip every N steps
wave_snap_skip      : 20
fault_snap_skip     : 2
grdsurf_snap_skip   : 2
