
# configure file for dynamic rupture simulations 
# in YAML format

# number of processors
nproc : 4
# simulation time length (in seconds)
simu_time_max : 12.0

# CFL number (<0.5)
cfl_number : 0.5

# mesh dir
mesh_dir : data
# output dir
data_dir : data

plasticity : 0

# snapshot output: skip every N steps
wave_snap_skip : 50
fault_snap_skip   : 2
grdsurf_snap_skip : 2
