
# configure file for dynamic rupture simulations 
# in YAML format

# number of processors
nproc : 4
# simulation time length (in seconds)
simu_time_max : 15.0

# CFL number (<0.5)
cfl_number : 0.5

# mesh dir
mesh_dir : data
# output dir
data_dir : data

# local stress: sigma0, tau0
input_stress_type : 1

# snapshot output: skip every N steps
wave_snap_skip      : 10
fault_snap_skip     : 10
grdsurf_snap_skip   : 10
